USE [master]
GO

/****** Object:  Database [SimpleRabbitMQ]    Script Date: 12/4/2019 3:03:39 PM ******/
--DROP DATABASE [SimpleRabbitMQ]
--GO

/****** Object:  Database [SimpleRabbitMQ]    Script Date: 12/4/2019 3:03:39 PM ******/
CREATE DATABASE [SimpleRabbitMQ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimpleRabbitMQ', FILENAME = N'C:\Users\MikeMcCarthy\SimpleRabbitMQ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SimpleRabbitMQ_log', FILENAME = N'C:\Users\MikeMcCarthy\SimpleRabbitMQ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleRabbitMQ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SimpleRabbitMQ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET ARITHABORT OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SimpleRabbitMQ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SimpleRabbitMQ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SimpleRabbitMQ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SimpleRabbitMQ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SimpleRabbitMQ] SET  MULTI_USER 
GO

ALTER DATABASE [SimpleRabbitMQ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SimpleRabbitMQ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SimpleRabbitMQ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SimpleRabbitMQ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SimpleRabbitMQ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SimpleRabbitMQ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SimpleRabbitMQ] SET  READ_WRITE 
GO

USE [SimpleRabbitMQ]
GO

/****** Object:  Table [dbo].[TestCommandHandler]    Script Date: 12/4/2019 3:09:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TestCommandHandler](
	[OrderId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TestCommandHandler] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [SimpleRabbitMQ]
GO

/****** Object:  Table [dbo].[TestEventHandler]    Script Date: 12/4/2019 3:09:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TestEventHandler](
	[OrderId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_TestEventHandler] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO